namespace ToolGood.Algorithm.math
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Generated from math.g4 by ANTLR 4.13.2
// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;
/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="mathParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
interface ImathVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg(mathParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Convert_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConvert_fun(mathParser.Convert_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CEILING_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCEILING_fun(mathParser.CEILING_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FACT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFACT_fun(mathParser.FACT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NPV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNPV_fun(mathParser.NPV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HASVALUE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHASVALUE_fun(mathParser.HASVALUE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSub_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSub_fun(mathParser.AddSub_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AVERAGEIF_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAVERAGEIF_fun(mathParser.AVERAGEIF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CASE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCASE_fun(mathParser.CASE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PARAM_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPARAM_fun(mathParser.PARAM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BESSELI_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBESSELI_fun(mathParser.BESSELI_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CSCH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCSCH_fun(mathParser.CSCH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>QUARTILE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQUARTILE_fun(mathParser.QUARTILE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UNICODE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUNICODE_fun(mathParser.UNICODE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FINV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFINV_fun(mathParser.FINV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SEC_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSEC_fun(mathParser.SEC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SYD_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSYD_fun(mathParser.SYD_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NOT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNOT_fun(mathParser.NOT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DAYS360_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDAYS360_fun(mathParser.DAYS360_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ACOTH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitACOTH_fun(mathParser.ACOTH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WEEKNUM_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWEEKNUM_fun(mathParser.WEEKNUM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>POISSON_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPOISSON_fun(mathParser.POISSON_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ISREGEX_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitISREGEX_fun(mathParser.ISREGEX_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COVARIANCES_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOVARIANCES_fun(mathParser.COVARIANCES_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STRINGSuffix_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTRINGSuffix_fun(mathParser.STRINGSuffix_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PERCENTILE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPERCENTILE_fun(mathParser.PERCENTILE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RATE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRATE_fun(mathParser.RATE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DiyFunction_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiyFunction_fun(mathParser.DiyFunction_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STAT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTAT_fun(mathParser.STAT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HAS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHAS_fun(mathParser.HAS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HYPGEOMDIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHYPGEOMDIST_fun(mathParser.HYPGEOMDIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PERMUT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPERMUT_fun(mathParser.PERMUT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RMB_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRMB_fun(mathParser.RMB_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SLOPE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSLOPE_fun(mathParser.SLOPE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CLEAN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCLEAN_fun(mathParser.CLEAN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NORMSINV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNORMSINV_fun(mathParser.NORMSINV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOGINV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOGINV_fun(mathParser.LOGINV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PPMT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPPMT_fun(mathParser.PPMT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WORKDAY_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWORKDAY_fun(mathParser.WORKDAY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>JIS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJIS_fun(mathParser.JIS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LCM_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLCM_fun(mathParser.LCM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BESSELJ_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBESSELJ_fun(mathParser.BESSELJ_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NORMINV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNORMINV_fun(mathParser.NORMINV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GAMMAINV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGAMMAINV_fun(mathParser.GAMMAINV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SQRT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSQRT_fun(mathParser.SQRT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ENCODE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitENCODE_fun(mathParser.ENCODE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DATE_TIME_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDATE_TIME_fun(mathParser.DATE_TIME_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DEGREES_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDEGREES_fun(mathParser.DEGREES_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MROUND_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMROUND_fun(mathParser.MROUND_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DATEDIF_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDATEDIF_fun(mathParser.DATEDIF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HMAC_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHMAC_fun(mathParser.HMAC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINT_fun(mathParser.INT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DDB_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDDB_fun(mathParser.DDB_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUMIF_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUMIF_fun(mathParser.SUMIF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PI_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPI_fun(mathParser.PI_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SQRTPI_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSQRTPI_fun(mathParser.SQRTPI_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CONCATENATE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCONCATENATE_fun(mathParser.CONCATENATE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FALSE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFALSE_fun(mathParser.FALSE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOG10_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOG10_fun(mathParser.LOG10_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>XIRR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXIRR_fun(mathParser.XIRR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NEGBINOMDIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNEGBINOMDIST_fun(mathParser.NEGBINOMDIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NETWORKDAYS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNETWORKDAYS_fun(mathParser.NETWORKDAYS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FACTDOUBLE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFACTDOUBLE_fun(mathParser.FACTDOUBLE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TIMEVALUE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTIMEVALUE_fun(mathParser.TIMEVALUE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GUID_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGUID_fun(mathParser.GUID_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPV_fun(mathParser.PV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>JSON_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJSON_fun(mathParser.JSON_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FIXED_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFIXED_fun(mathParser.FIXED_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GetJsonValue_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetJsonValue_fun(mathParser.GetJsonValue_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TINV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTINV_fun(mathParser.TINV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EDATE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEDATE_fun(mathParser.EDATE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SIGN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSIGN_fun(mathParser.SIGN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EOMONTH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEOMONTH_fun(mathParser.EOMONTH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FLOOR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFLOOR_fun(mathParser.FLOOR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LEN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLEN_fun(mathParser.LEN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ACOS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitACOS_fun(mathParser.ACOS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NUM_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNUM_fun(mathParser.NUM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COSH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOSH_fun(mathParser.COSH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CORREL_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCORREL_fun(mathParser.CORREL_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GESTEP_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGESTEP_fun(mathParser.GESTEP_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>XNPV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXNPV_fun(mathParser.XNPV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>QUOTIENT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQUOTIENT_fun(mathParser.QUOTIENT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FORECAST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFORECAST_fun(mathParser.FORECAST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BESSELY_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBESSELY_fun(mathParser.BESSELY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SEARCH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSEARCH_fun(mathParser.SEARCH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IRR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIRR_fun(mathParser.IRR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ACOT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitACOT_fun(mathParser.ACOT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ROUNDUP_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitROUNDUP_fun(mathParser.ROUNDUP_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COMBIN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOMBIN_fun(mathParser.COMBIN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CODE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCODE_fun(mathParser.CODE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CSC_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCSC_fun(mathParser.CSC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ASINH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitASINH_fun(mathParser.ASINH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COTH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOTH_fun(mathParser.COTH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SIN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSIN_fun(mathParser.SIN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUBSTRING_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUBSTRING_fun(mathParser.SUBSTRING_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RANDBETWEEN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRANDBETWEEN_fun(mathParser.RANDBETWEEN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOG_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOG_fun(mathParser.LOG_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOOK_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOOK_fun(mathParser.LOOK_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AndOr_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndOr_fun(mathParser.AndOr_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Array_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_fun(mathParser.Array_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ROUND_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitROUND_fun(mathParser.ROUND_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EXP_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEXP_fun(mathParser.EXP_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COUNTIF_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOUNTIF_fun(mathParser.COUNTIF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DATE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDATE_fun(mathParser.DATE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PARAMETER_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPARAMETER_fun(mathParser.PARAMETER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BESSELK_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBESSELK_fun(mathParser.BESSELK_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SPLIT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSPLIT_fun(mathParser.SPLIT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>REGEXREPLACE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitREGEXREPLACE_fun(mathParser.REGEXREPLACE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COVAR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOVAR_fun(mathParser.COVAR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LARGE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLARGE_fun(mathParser.LARGE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUMXMY2_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUMXMY2_fun(mathParser.SUMXMY2_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SERIESSUM_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSERIESSUM_fun(mathParser.SERIESSUM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TIMESTAMP_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTIMESTAMP_fun(mathParser.TIMESTAMP_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RANK_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRANK_fun(mathParser.RANK_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PMT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPMT_fun(mathParser.PMT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TRIM_SE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTRIM_SE_fun(mathParser.TRIM_SE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ROMAN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitROMAN_fun(mathParser.ROMAN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DELTA_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDELTA_fun(mathParser.DELTA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VALUE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVALUE_fun(mathParser.VALUE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WEIBULL_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWEIBULL_fun(mathParser.WEIBULL_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PEARSON_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPEARSON_fun(mathParser.PEARSON_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLR_fun(mathParser.LR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BINOMDIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBINOMDIST_fun(mathParser.BINOMDIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Judge_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJudge_fun(mathParser.Judge_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ERFC_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitERFC_fun(mathParser.ERFC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BETAINV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBETAINV_fun(mathParser.BETAINV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TAN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTAN_fun(mathParser.TAN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IFERROR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIFERROR_fun(mathParser.IFERROR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FDIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFDIST_fun(mathParser.FDIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INDEXOF_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINDEXOF_fun(mathParser.INDEXOF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>REMOVE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitREMOVE_fun(mathParser.REMOVE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EXPONDIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEXPONDIST_fun(mathParser.EXPONDIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HASH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHASH_fun(mathParser.HASH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SMALL_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSMALL_fun(mathParser.SMALL_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IFS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIFS_fun(mathParser.IFS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ODD_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitODD_fun(mathParser.ODD_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUMPRODUCT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUMPRODUCT_fun(mathParser.SUMPRODUCT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MID_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMID_fun(mathParser.MID_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PERCENTRANK_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPERCENTRANK_fun(mathParser.PERCENTRANK_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NORMSDIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNORMSDIST_fun(mathParser.NORMSDIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MOD_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMOD_fun(mathParser.MOD_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CHAR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCHAR_fun(mathParser.CHAR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>REGEX_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitREGEX_fun(mathParser.REGEX_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>REPLACE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitREPLACE_fun(mathParser.REPLACE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ACOSH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitACOSH_fun(mathParser.ACOSH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MIRR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMIRR_fun(mathParser.MIRR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ASC_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitASC_fun(mathParser.ASC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOS_fun(mathParser.COS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLN_fun(mathParser.LN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STRING_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTRING_fun(mathParser.STRING_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PRODUCT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPRODUCT_fun(mathParser.PRODUCT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EXACT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEXACT_fun(mathParser.EXACT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUMSQ_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUMSQ_fun(mathParser.SUMSQ_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DAYS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDAYS_fun(mathParser.DAYS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GAMMADIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGAMMADIST_fun(mathParser.GAMMADIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TODAY_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTODAY_fun(mathParser.TODAY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ERROR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitERROR_fun(mathParser.ERROR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ATAN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitATAN_fun(mathParser.ATAN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ERF_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitERF_fun(mathParser.ERF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUMX2PY2_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUMX2PY2_fun(mathParser.SUMX2PY2_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>E_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitE_fun(mathParser.E_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TRIM_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTRIM_fun(mathParser.TRIM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RADIANS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRADIANS_fun(mathParser.RADIANS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GAMMALN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGAMMALN_fun(mathParser.GAMMALN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TEXT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTEXT_fun(mathParser.TEXT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FISHER_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFISHER_fun(mathParser.FISHER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ISNULLOR_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitISNULLOR_fun(mathParser.ISNULLOR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayJson_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayJson_fun(mathParser.ArrayJson_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MULTINOMIAL_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMULTINOMIAL_fun(mathParser.MULTINOMIAL_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NORMDIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNORMDIST_fun(mathParser.NORMDIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IPMT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIPMT_fun(mathParser.IPMT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Bracket_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_fun(mathParser.Bracket_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SLN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSLN_fun(mathParser.SLN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BETADIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBETADIST_fun(mathParser.BETADIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ATANH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitATANH_fun(mathParser.ATANH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NOW_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNOW_fun(mathParser.NOW_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>POWER_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPOWER_fun(mathParser.POWER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PROPER_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPROPER_fun(mathParser.PROPER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TRUNC_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTRUNC_fun(mathParser.TRUNC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GCD_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGCD_fun(mathParser.GCD_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TANH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTANH_fun(mathParser.TANH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SINH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSINH_fun(mathParser.SINH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIS_fun(mathParser.IS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SWITCH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSWITCH_fun(mathParser.SWITCH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ISNULL_check_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitISNULL_check_fun(mathParser.ISNULL_check_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ABS_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitABS_fun(mathParser.ABS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ROUNDDOWN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitROUNDDOWN_fun(mathParser.ROUNDDOWN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IF_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIF_fun(mathParser.IF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>JOIN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJOIN_fun(mathParser.JOIN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FIND_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFIND_fun(mathParser.FIND_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUBSTITUTE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUBSTITUTE_fun(mathParser.SUBSTITUTE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Percentage_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPercentage_fun(mathParser.Percentage_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>REPT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitREPT_fun(mathParser.REPT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFV_fun(mathParser.FV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ASIN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitASIN_fun(mathParser.ASIN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUMX2MY2_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUMX2MY2_fun(mathParser.SUMX2MY2_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDiv_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDiv_fun(mathParser.MulDiv_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NPER_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNPER_fun(mathParser.NPER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>T_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitT_fun(mathParser.T_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WEEKDAY_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWEEKDAY_fun(mathParser.WEEKDAY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NULL_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNULL_fun(mathParser.NULL_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TDIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTDIST_fun(mathParser.TDIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DATEVALUE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDATEVALUE_fun(mathParser.DATEVALUE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EVEN_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEVEN_fun(mathParser.EVEN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOGNORMDIST_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOGNORMDIST_fun(mathParser.LOGNORMDIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DB_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDB_fun(mathParser.DB_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOGIC_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOGIC_fun(mathParser.LOGIC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TRUE_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTRUE_fun(mathParser.TRUE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INTERCEPT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINTERCEPT_fun(mathParser.INTERCEPT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FISHERINV_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFISHERINV_fun(mathParser.FISHERINV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TIME_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTIME_fun(mathParser.TIME_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ARABIC_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitARABIC_fun(mathParser.ARABIC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ATAN2_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitATAN2_fun(mathParser.ATAN2_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SECH_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSECH_fun(mathParser.SECH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOT_fun(mathParser.COT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Version_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersion_fun(mathParser.Version_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>YEARFRAC_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYEARFRAC_fun(mathParser.YEARFRAC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RAND_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRAND_fun(mathParser.RAND_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ADD_DateTime_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitADD_DateTime_fun(mathParser.ADD_DateTime_funContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum(mathParser.NumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.arrayJson"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayJson(mathParser.ArrayJsonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.parameter2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter2(mathParser.Parameter2Context context);
}

}