//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from math.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class mathParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, NUM=30, STRING=31, NULL=32, 
		UNIT=33, T=34, PARAMETER=35, WS=36, COMMENT=37, LINE_COMMENT=38;
	public const int
		RULE_prog = 0, RULE_expr = 1, RULE_num = 2, RULE_arrayJson = 3;
	public static readonly string[] ruleNames = {
		"prog", "expr", "num", "arrayJson"
	};

	private static readonly string[] _LiteralNames = {
		null, "'.'", "'('", "','", "')'", "'['", "']'", "'!'", "'%'", "'*'", "'/'", 
		"'+'", "'-'", "'&'", "'>'", "'>='", "'<'", "'<='", "'='", "'=='", "'==='", 
		"'!=='", "'!='", "'<>'", "'&&'", "'||'", "'?'", "':'", "'{'", "'}'", null, 
		null, "'NULL'", null, "'T'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, "NUM", "STRING", "NULL", "UNIT", "T", 
		"PARAMETER", "WS", "COMMENT", "LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "math.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static mathParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public mathParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public mathParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(mathParser.Eof, 0); }
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 8;
			expr(0);
			State = 9;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class IF_funContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public IF_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIF_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Judge_funContext : ExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Judge_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJudge_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AndOr_funContext : ExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public AndOr_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndOr_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Percentage_funContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Percentage_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPercentage_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DiyFunction_funContext : ExprContext {
		public IToken f;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T() { return GetToken(mathParser.T, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNIT() { return GetToken(mathParser.UNIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER() { return GetToken(mathParser.PARAMETER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public DiyFunction_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiyFunction_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class STRING_funContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(mathParser.STRING, 0); }
		public STRING_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSTRING_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AddSub_funContext : ExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public AddSub_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAddSub_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ArrayJson_funContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArrayJsonContext[] arrayJson() {
			return GetRuleContexts<ArrayJsonContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArrayJsonContext arrayJson(int i) {
			return GetRuleContext<ArrayJsonContext>(i);
		}
		public ArrayJson_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayJson_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GetJsonValue_funContext : ExprContext {
		public IToken p;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER() { return GetToken(mathParser.PARAMETER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T() { return GetToken(mathParser.T, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNIT() { return GetToken(mathParser.UNIT, 0); }
		public GetJsonValue_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGetJsonValue_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Array_funContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Array_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MulDiv_funContext : ExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public MulDiv_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMulDiv_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NOT_funContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NOT_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNOT_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Bracket_funContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Bracket_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBracket_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PARAMETER_funContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER() { return GetToken(mathParser.PARAMETER, 0); }
		public PARAMETER_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPARAMETER_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NUM_funContext : ExprContext {
		public IToken unit;
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNIT() { return GetToken(mathParser.UNIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T() { return GetToken(mathParser.T, 0); }
		public NUM_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNUM_fun(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NULL_funContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(mathParser.NULL, 0); }
		public NULL_funContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNULL_fun(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				{
				_localctx = new Bracket_funContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 12;
				Match(T__1);
				State = 13;
				expr(0);
				State = 14;
				Match(T__3);
				}
				break;
			case 2:
				{
				_localctx = new NOT_funContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 16;
				Match(T__6);
				State = 17;
				expr(16);
				}
				break;
			case 3:
				{
				_localctx = new DiyFunction_funContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 18;
				((DiyFunction_funContext)_localctx).f = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 60129542144L) != 0)) ) {
					((DiyFunction_funContext)_localctx).f = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 19;
				Match(T__1);
				State = 28;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 67914174628L) != 0)) {
					{
					State = 20;
					expr(0);
					State = 25;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__2) {
						{
						{
						State = 21;
						Match(T__2);
						State = 22;
						expr(0);
						}
						}
						State = 27;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 30;
				Match(T__3);
				}
				break;
			case 4:
				{
				_localctx = new ArrayJson_funContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 31;
				Match(T__27);
				State = 32;
				arrayJson();
				State = 37;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 33;
						Match(T__2);
						State = 34;
						arrayJson();
						}
						} 
					}
					State = 39;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
				}
				State = 43;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__2) {
					{
					{
					State = 40;
					Match(T__2);
					}
					}
					State = 45;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 46;
				Match(T__28);
				}
				break;
			case 5:
				{
				_localctx = new Array_funContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 48;
				Match(T__4);
				State = 49;
				expr(0);
				State = 54;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 50;
						Match(T__2);
						State = 51;
						expr(0);
						}
						} 
					}
					State = 56;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				}
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__2) {
					{
					{
					State = 57;
					Match(T__2);
					}
					}
					State = 62;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 63;
				Match(T__5);
				}
				break;
			case 6:
				{
				_localctx = new PARAMETER_funContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 65;
				Match(PARAMETER);
				}
				break;
			case 7:
				{
				_localctx = new NUM_funContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 66;
				num();
				State = 68;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
				case 1:
					{
					State = 67;
					((NUM_funContext)_localctx).unit = TokenStream.LT(1);
					_la = TokenStream.LA(1);
					if ( !(_la==UNIT || _la==T) ) {
						((NUM_funContext)_localctx).unit = ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
					break;
				}
				}
				break;
			case 8:
				{
				_localctx = new STRING_funContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 70;
				Match(STRING);
				}
				break;
			case 9:
				{
				_localctx = new NULL_funContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 71;
				Match(NULL);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 129;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 127;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
					case 1:
						{
						_localctx = new MulDiv_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 74;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 75;
						((MulDiv_funContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 1792L) != 0)) ) {
							((MulDiv_funContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 76;
						expr(15);
						}
						break;
					case 2:
						{
						_localctx = new AddSub_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 77;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 78;
						((AddSub_funContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 14336L) != 0)) ) {
							((AddSub_funContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 79;
						expr(14);
						}
						break;
					case 3:
						{
						_localctx = new Judge_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 80;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 81;
						((Judge_funContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 245760L) != 0)) ) {
							((Judge_funContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 82;
						expr(13);
						}
						break;
					case 4:
						{
						_localctx = new Judge_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 83;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 84;
						((Judge_funContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 16515072L) != 0)) ) {
							((Judge_funContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 85;
						expr(12);
						}
						break;
					case 5:
						{
						_localctx = new AndOr_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 86;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 87;
						((AndOr_funContext)_localctx).op = Match(T__23);
						State = 88;
						expr(11);
						}
						break;
					case 6:
						{
						_localctx = new AndOr_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 89;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 90;
						((AndOr_funContext)_localctx).op = Match(T__24);
						State = 91;
						expr(10);
						}
						break;
					case 7:
						{
						_localctx = new IF_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 92;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 93;
						Match(T__25);
						State = 94;
						expr(0);
						State = 95;
						Match(T__26);
						State = 96;
						expr(9);
						}
						break;
					case 8:
						{
						_localctx = new DiyFunction_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 98;
						if (!(Precpred(Context, 21))) throw new FailedPredicateException(this, "Precpred(Context, 21)");
						State = 99;
						Match(T__0);
						State = 100;
						((DiyFunction_funContext)_localctx).f = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 60129542144L) != 0)) ) {
							((DiyFunction_funContext)_localctx).f = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 101;
						Match(T__1);
						State = 110;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 67914174628L) != 0)) {
							{
							State = 102;
							expr(0);
							State = 107;
							ErrorHandler.Sync(this);
							_la = TokenStream.LA(1);
							while (_la==T__2) {
								{
								{
								State = 103;
								Match(T__2);
								State = 104;
								expr(0);
								}
								}
								State = 109;
								ErrorHandler.Sync(this);
								_la = TokenStream.LA(1);
							}
							}
						}

						State = 112;
						Match(T__3);
						}
						break;
					case 9:
						{
						_localctx = new GetJsonValue_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 113;
						if (!(Precpred(Context, 20))) throw new FailedPredicateException(this, "Precpred(Context, 20)");
						State = 114;
						Match(T__4);
						State = 115;
						Match(PARAMETER);
						State = 116;
						Match(T__5);
						}
						break;
					case 10:
						{
						_localctx = new GetJsonValue_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 117;
						if (!(Precpred(Context, 19))) throw new FailedPredicateException(this, "Precpred(Context, 19)");
						State = 118;
						Match(T__4);
						State = 119;
						expr(0);
						State = 120;
						Match(T__5);
						}
						break;
					case 11:
						{
						_localctx = new GetJsonValue_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 122;
						if (!(Precpred(Context, 18))) throw new FailedPredicateException(this, "Precpred(Context, 18)");
						State = 123;
						Match(T__0);
						State = 124;
						((GetJsonValue_funContext)_localctx).p = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 60129542144L) != 0)) ) {
							((GetJsonValue_funContext)_localctx).p = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						}
						break;
					case 12:
						{
						_localctx = new Percentage_funContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 125;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 126;
						Match(T__7);
						}
						break;
					}
					} 
				}
				State = 131;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class NumContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUM() { return GetToken(mathParser.NUM, 0); }
		public NumContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_num; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNum(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumContext num() {
		NumContext _localctx = new NumContext(Context, State);
		EnterRule(_localctx, 4, RULE_num);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__11) {
				{
				State = 132;
				Match(T__11);
				}
			}

			State = 135;
			Match(NUM);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayJsonContext : ParserRuleContext {
		public IToken key;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUM() { return GetToken(mathParser.NUM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(mathParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(mathParser.NULL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T() { return GetToken(mathParser.T, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNIT() { return GetToken(mathParser.UNIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER() { return GetToken(mathParser.PARAMETER, 0); }
		public ArrayJsonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayJson; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ImathVisitor<TResult> typedVisitor = visitor as ImathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayJson(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayJsonContext arrayJson() {
		ArrayJsonContext _localctx = new ArrayJsonContext(Context, State);
		EnterRule(_localctx, 6, RULE_arrayJson);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137;
			_localctx.key = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 67645734912L) != 0)) ) {
				_localctx.key = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 138;
			Match(T__26);
			State = 139;
			expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 14);
		case 1: return Precpred(Context, 13);
		case 2: return Precpred(Context, 12);
		case 3: return Precpred(Context, 11);
		case 4: return Precpred(Context, 10);
		case 5: return Precpred(Context, 9);
		case 6: return Precpred(Context, 8);
		case 7: return Precpred(Context, 21);
		case 8: return Precpred(Context, 20);
		case 9: return Precpred(Context, 19);
		case 10: return Precpred(Context, 18);
		case 11: return Precpred(Context, 15);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,38,142,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,1,0,1,0,1,0,1,1,1,1,1,1,1,1,
		1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,1,24,8,1,10,1,12,1,27,9,1,3,1,29,8,1,
		1,1,1,1,1,1,1,1,1,1,5,1,36,8,1,10,1,12,1,39,9,1,1,1,5,1,42,8,1,10,1,12,
		1,45,9,1,1,1,1,1,1,1,1,1,1,1,1,1,5,1,53,8,1,10,1,12,1,56,9,1,1,1,5,1,59,
		8,1,10,1,12,1,62,9,1,1,1,1,1,1,1,1,1,1,1,3,1,69,8,1,1,1,1,1,3,1,73,8,1,
		1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
		1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,1,106,8,1,10,1,
		12,1,109,9,1,3,1,111,8,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
		1,1,1,1,1,1,1,5,1,128,8,1,10,1,12,1,131,9,1,1,2,3,2,134,8,2,1,2,1,2,1,
		3,1,3,1,3,1,3,1,3,0,1,2,4,0,2,4,6,0,7,1,0,33,35,1,0,33,34,1,0,8,10,1,0,
		11,13,1,0,14,17,1,0,18,23,1,0,30,35,167,0,8,1,0,0,0,2,72,1,0,0,0,4,133,
		1,0,0,0,6,137,1,0,0,0,8,9,3,2,1,0,9,10,5,0,0,1,10,1,1,0,0,0,11,12,6,1,
		-1,0,12,13,5,2,0,0,13,14,3,2,1,0,14,15,5,4,0,0,15,73,1,0,0,0,16,17,5,7,
		0,0,17,73,3,2,1,16,18,19,7,0,0,0,19,28,5,2,0,0,20,25,3,2,1,0,21,22,5,3,
		0,0,22,24,3,2,1,0,23,21,1,0,0,0,24,27,1,0,0,0,25,23,1,0,0,0,25,26,1,0,
		0,0,26,29,1,0,0,0,27,25,1,0,0,0,28,20,1,0,0,0,28,29,1,0,0,0,29,30,1,0,
		0,0,30,73,5,4,0,0,31,32,5,28,0,0,32,37,3,6,3,0,33,34,5,3,0,0,34,36,3,6,
		3,0,35,33,1,0,0,0,36,39,1,0,0,0,37,35,1,0,0,0,37,38,1,0,0,0,38,43,1,0,
		0,0,39,37,1,0,0,0,40,42,5,3,0,0,41,40,1,0,0,0,42,45,1,0,0,0,43,41,1,0,
		0,0,43,44,1,0,0,0,44,46,1,0,0,0,45,43,1,0,0,0,46,47,5,29,0,0,47,73,1,0,
		0,0,48,49,5,5,0,0,49,54,3,2,1,0,50,51,5,3,0,0,51,53,3,2,1,0,52,50,1,0,
		0,0,53,56,1,0,0,0,54,52,1,0,0,0,54,55,1,0,0,0,55,60,1,0,0,0,56,54,1,0,
		0,0,57,59,5,3,0,0,58,57,1,0,0,0,59,62,1,0,0,0,60,58,1,0,0,0,60,61,1,0,
		0,0,61,63,1,0,0,0,62,60,1,0,0,0,63,64,5,6,0,0,64,73,1,0,0,0,65,73,5,35,
		0,0,66,68,3,4,2,0,67,69,7,1,0,0,68,67,1,0,0,0,68,69,1,0,0,0,69,73,1,0,
		0,0,70,73,5,31,0,0,71,73,5,32,0,0,72,11,1,0,0,0,72,16,1,0,0,0,72,18,1,
		0,0,0,72,31,1,0,0,0,72,48,1,0,0,0,72,65,1,0,0,0,72,66,1,0,0,0,72,70,1,
		0,0,0,72,71,1,0,0,0,73,129,1,0,0,0,74,75,10,14,0,0,75,76,7,2,0,0,76,128,
		3,2,1,15,77,78,10,13,0,0,78,79,7,3,0,0,79,128,3,2,1,14,80,81,10,12,0,0,
		81,82,7,4,0,0,82,128,3,2,1,13,83,84,10,11,0,0,84,85,7,5,0,0,85,128,3,2,
		1,12,86,87,10,10,0,0,87,88,5,24,0,0,88,128,3,2,1,11,89,90,10,9,0,0,90,
		91,5,25,0,0,91,128,3,2,1,10,92,93,10,8,0,0,93,94,5,26,0,0,94,95,3,2,1,
		0,95,96,5,27,0,0,96,97,3,2,1,9,97,128,1,0,0,0,98,99,10,21,0,0,99,100,5,
		1,0,0,100,101,7,0,0,0,101,110,5,2,0,0,102,107,3,2,1,0,103,104,5,3,0,0,
		104,106,3,2,1,0,105,103,1,0,0,0,106,109,1,0,0,0,107,105,1,0,0,0,107,108,
		1,0,0,0,108,111,1,0,0,0,109,107,1,0,0,0,110,102,1,0,0,0,110,111,1,0,0,
		0,111,112,1,0,0,0,112,128,5,4,0,0,113,114,10,20,0,0,114,115,5,5,0,0,115,
		116,5,35,0,0,116,128,5,6,0,0,117,118,10,19,0,0,118,119,5,5,0,0,119,120,
		3,2,1,0,120,121,5,6,0,0,121,128,1,0,0,0,122,123,10,18,0,0,123,124,5,1,
		0,0,124,128,7,0,0,0,125,126,10,15,0,0,126,128,5,8,0,0,127,74,1,0,0,0,127,
		77,1,0,0,0,127,80,1,0,0,0,127,83,1,0,0,0,127,86,1,0,0,0,127,89,1,0,0,0,
		127,92,1,0,0,0,127,98,1,0,0,0,127,113,1,0,0,0,127,117,1,0,0,0,127,122,
		1,0,0,0,127,125,1,0,0,0,128,131,1,0,0,0,129,127,1,0,0,0,129,130,1,0,0,
		0,130,3,1,0,0,0,131,129,1,0,0,0,132,134,5,12,0,0,133,132,1,0,0,0,133,134,
		1,0,0,0,134,135,1,0,0,0,135,136,5,30,0,0,136,5,1,0,0,0,137,138,7,6,0,0,
		138,139,5,27,0,0,139,140,3,2,1,0,140,7,1,0,0,0,13,25,28,37,43,54,60,68,
		72,107,110,127,129,133
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
