namespace ToolGood.Algorithm.math
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from math.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="mathParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>


interface ImathVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg(mathParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IF_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIF_fun(mathParser.IF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Judge_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJudge_fun(mathParser.Judge_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AndOr_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndOr_fun(mathParser.AndOr_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Percentage_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPercentage_fun(mathParser.Percentage_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DiyFunction_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiyFunction_fun(mathParser.DiyFunction_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STRING_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTRING_fun(mathParser.STRING_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSub_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSub_fun(mathParser.AddSub_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayJson_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayJson_fun(mathParser.ArrayJson_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GetJsonValue_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetJsonValue_fun(mathParser.GetJsonValue_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Array_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_fun(mathParser.Array_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDiv_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDiv_fun(mathParser.MulDiv_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NOT_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNOT_fun(mathParser.NOT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Bracket_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_fun(mathParser.Bracket_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PARAMETER_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPARAMETER_fun(mathParser.PARAMETER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NUM_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNUM_fun(mathParser.NUM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NULL_fun</c>
	/// labeled alternative in <see cref="mathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNULL_fun(mathParser.NULL_funContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum(mathParser.NumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mathParser.arrayJson"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayJson(mathParser.ArrayJsonContext context);
}

}