//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from math.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Tree;

interface ImathVisitor<Result> : IParseTreeVisitor<Result>
{
    Result VisitProg(mathParser.ProgContext context);
    Result VisitCEILING_fun(mathParser.CEILING_funContext context);
    Result VisitFACT_fun(mathParser.FACT_funContext context);
    Result VisitREGEXREPALCE_fun(mathParser.REGEXREPALCE_funContext context);
    Result VisitAddSub_fun(mathParser.AddSub_funContext context);
    Result VisitAVERAGEIF_fun(mathParser.AVERAGEIF_funContext context);
    Result VisitRIGHT_fun(mathParser.RIGHT_funContext context);
    Result VisitOCT2BIN_fun(mathParser.OCT2BIN_funContext context);
    Result VisitQUARTILE_fun(mathParser.QUARTILE_funContext context);
    Result VisitFINV_fun(mathParser.FINV_funContext context);
    Result VisitNOT_fun(mathParser.NOT_funContext context);
    Result VisitDAYS360_fun(mathParser.DAYS360_funContext context);
    Result VisitWEEKNUM_fun(mathParser.WEEKNUM_funContext context);
    Result VisitPOISSON_fun(mathParser.POISSON_funContext context);
    Result VisitISREGEX_fun(mathParser.ISREGEX_funContext context);
    Result VisitPERCENTILE_fun(mathParser.PERCENTILE_funContext context);
    Result VisitSHA256_fun(mathParser.SHA256_funContext context);
    Result VisitHYPGEOMDIST_fun(mathParser.HYPGEOMDIST_funContext context);
    Result VisitPERMUT_fun(mathParser.PERMUT_funContext context);
    Result VisitTRIMSTART_fun(mathParser.TRIMSTART_funContext context);
    Result VisitRMB_fun(mathParser.RMB_funContext context);
    Result VisitDEC2HEX_fun(mathParser.DEC2HEX_funContext context);
    Result VisitCLEAN_fun(mathParser.CLEAN_funContext context);
    Result VisitLOWER_fun(mathParser.LOWER_funContext context);
    Result VisitOR_fun(mathParser.OR_funContext context);
    Result VisitNORMSINV_fun(mathParser.NORMSINV_funContext context);
    Result VisitLEFT_fun(mathParser.LEFT_funContext context);
    Result VisitISEVEN_fun(mathParser.ISEVEN_funContext context);
    Result VisitLOGINV_fun(mathParser.LOGINV_funContext context);
    Result VisitWORKDAY_fun(mathParser.WORKDAY_funContext context);
    Result VisitISERROR_fun(mathParser.ISERROR_funContext context);
    Result VisitBIN2DEC_fun(mathParser.BIN2DEC_funContext context);
    Result VisitJIS_fun(mathParser.JIS_funContext context);
    Result VisitCRC32_fun(mathParser.CRC32_funContext context);
    Result VisitLCM_fun(mathParser.LCM_funContext context);
    Result VisitHARMEAN_fun(mathParser.HARMEAN_funContext context);
    Result VisitNORMINV_fun(mathParser.NORMINV_funContext context);
    Result VisitGAMMAINV_fun(mathParser.GAMMAINV_funContext context);
    Result VisitSQRT_fun(mathParser.SQRT_funContext context);
    Result VisitDEGREES_fun(mathParser.DEGREES_funContext context);
    Result VisitMROUND_fun(mathParser.MROUND_funContext context);
    Result VisitDATEDIF_fun(mathParser.DATEDIF_funContext context);
    Result VisitTRIMEND_fun(mathParser.TRIMEND_funContext context);

    Result VisitISLOGICAL_fun(mathParser.ISLOGICAL_funContext context);
    Result VisitINT_fun(mathParser.INT_funContext context);
    Result VisitSUMIF_fun(mathParser.SUMIF_funContext context);
    Result VisitHEX2OCT_fun(mathParser.HEX2OCT_funContext context);
    Result VisitPI_fun(mathParser.PI_funContext context);
    Result VisitYEAR_fun(mathParser.YEAR_funContext context);
    Result VisitSQRTPI_fun(mathParser.SQRTPI_funContext context);
    Result VisitCONCATENATE_fun(mathParser.CONCATENATE_funContext context);
    Result VisitCOUNT_fun(mathParser.COUNT_funContext context);
    Result VisitFALSE_fun(mathParser.FALSE_funContext context);
    Result VisitHTMLENCODE_fun(mathParser.HTMLENCODE_funContext context);
    Result VisitBASE64URLTOTEXT_fun(mathParser.BASE64URLTOTEXT_funContext context);
    Result VisitLOG10_fun(mathParser.LOG10_funContext context);
    Result VisitISTEXT_fun(mathParser.ISTEXT_funContext context);
    Result VisitNEGBINOMDIST_fun(mathParser.NEGBINOMDIST_funContext context);
    Result VisitNETWORKDAYS_fun(mathParser.NETWORKDAYS_funContext context);
    Result VisitFACTDOUBLE_fun(mathParser.FACTDOUBLE_funContext context);
    Result VisitTIMEVALUE_fun(mathParser.TIMEVALUE_funContext context);
    Result VisitAVEDEV_fun(mathParser.AVEDEV_funContext context);
    Result VisitGUID_fun(mathParser.GUID_funContext context);
    Result VisitJSON_fun(mathParser.JSON_funContext context);
    Result VisitFIXED_fun(mathParser.FIXED_funContext context);
    Result VisitGetJsonValue_fun(mathParser.GetJsonValue_funContext context);
    Result VisitTINV_fun(mathParser.TINV_funContext context);
    Result VisitEDATE_fun(mathParser.EDATE_funContext context);
    Result VisitGEOMEAN_fun(mathParser.GEOMEAN_funContext context);
    Result VisitVAR_fun(mathParser.VAR_funContext context);
    Result VisitSIGN_fun(mathParser.SIGN_funContext context);
    Result VisitEOMONTH_fun(mathParser.EOMONTH_funContext context);
    Result VisitFLOOR_fun(mathParser.FLOOR_funContext context);
    Result VisitHOUR_fun(mathParser.HOUR_funContext context);
    Result VisitLEN_fun(mathParser.LEN_funContext context);
    Result VisitACOS_fun(mathParser.ACOS_funContext context);
    Result VisitISNULLORWHITESPACE_fun(mathParser.ISNULLORWHITESPACE_funContext context);
    Result VisitNUM_fun(mathParser.NUM_funContext context);
    Result VisitCOSH_fun(mathParser.COSH_funContext context);
    Result VisitQUOTIENT_fun(mathParser.QUOTIENT_funContext context);
    Result VisitOCT2DEC_fun(mathParser.OCT2DEC_funContext context);
    Result VisitSEARCH_fun(mathParser.SEARCH_funContext context);
    Result VisitROUNDUP_fun(mathParser.ROUNDUP_funContext context);
    Result VisitCOMBIN_fun(mathParser.COMBIN_funContext context);
    Result VisitCODE_fun(mathParser.CODE_funContext context);
    Result VisitASINH_fun(mathParser.ASINH_funContext context);
    Result VisitSIN_fun(mathParser.SIN_funContext context);
    Result VisitSUBSTRING_fun(mathParser.SUBSTRING_funContext context);
    Result VisitRANDBETWEEN_fun(mathParser.RANDBETWEEN_funContext context);
    Result VisitAVERAGE_fun(mathParser.AVERAGE_funContext context);
    Result VisitLOG_fun(mathParser.LOG_funContext context);
    Result VisitHMACSHA512_fun(mathParser.HMACSHA512_funContext context);
    Result VisitAndOr_fun(mathParser.AndOr_funContext context);
    Result VisitSTDEVP_fun(mathParser.STDEVP_funContext context);
    Result VisitArray_fun(mathParser.Array_funContext context);
    Result VisitROUND_fun(mathParser.ROUND_funContext context);
    Result VisitEXP_fun(mathParser.EXP_funContext context);
    Result VisitCOUNTIF_fun(mathParser.COUNTIF_funContext context);
    Result VisitVARP_fun(mathParser.VARP_funContext context);
    Result VisitREMOVEEND_fun(mathParser.REMOVEEND_funContext context);
    Result VisitDATE_fun(mathParser.DATE_funContext context);
    Result VisitPARAMETER_fun(mathParser.PARAMETER_funContext context);
    Result VisitSPLIT_fun(mathParser.SPLIT_funContext context);
    Result VisitURLDECODE_fun(mathParser.URLDECODE_funContext context);
    Result VisitLARGE_fun(mathParser.LARGE_funContext context);
    Result VisitVALUE_fun(mathParser.VALUE_funContext context);
    Result VisitDAY_fun(mathParser.DAY_funContext context);
    Result VisitWEIBULL_fun(mathParser.WEIBULL_funContext context);
    Result VisitHMACSHA256_fun(mathParser.HMACSHA256_funContext context);
    Result VisitBINOMDIST_fun(mathParser.BINOMDIST_funContext context);
    Result VisitJudge_fun(mathParser.Judge_funContext context);
    Result VisitDEVSQ_fun(mathParser.DEVSQ_funContext context);
    Result VisitMODE_fun(mathParser.MODE_funContext context);
    Result VisitBETAINV_fun(mathParser.BETAINV_funContext context);
    Result VisitMAX_fun(mathParser.MAX_funContext context);
    Result VisitMINUTE_fun(mathParser.MINUTE_funContext context);
    Result VisitTAN_fun(mathParser.TAN_funContext context);
    Result VisitIFERROR_fun(mathParser.IFERROR_funContext context);
    Result VisitFDIST_fun(mathParser.FDIST_funContext context);
    Result VisitINDEXOF_fun(mathParser.INDEXOF_funContext context);
    Result VisitUPPER_fun(mathParser.UPPER_funContext context);
    Result VisitHTMLDECODE_fun(mathParser.HTMLDECODE_funContext context);
    Result VisitEXPONDIST_fun(mathParser.EXPONDIST_funContext context);
    Result VisitDEC2BIN_fun(mathParser.DEC2BIN_funContext context);
    Result VisitHEX2DEC_fun(mathParser.HEX2DEC_funContext context);
    Result VisitSMALL_fun(mathParser.SMALL_funContext context);
    Result VisitODD_fun(mathParser.ODD_funContext context);
    Result VisitTEXTTOBASE64_fun(mathParser.TEXTTOBASE64_funContext context);
    Result VisitMID_fun(mathParser.MID_funContext context);
    Result VisitPERCENTRANK_fun(mathParser.PERCENTRANK_funContext context);
    Result VisitSTDEV_fun(mathParser.STDEV_funContext context);
    Result VisitNORMSDIST_fun(mathParser.NORMSDIST_funContext context);
    Result VisitISNUMBER_fun(mathParser.ISNUMBER_funContext context);
    Result VisitLASTINDEXOF_fun(mathParser.LASTINDEXOF_funContext context);
    Result VisitMOD_fun(mathParser.MOD_funContext context);
    Result VisitCHAR_fun(mathParser.CHAR_funContext context);
    Result VisitREGEX_fun(mathParser.REGEX_funContext context);
    Result VisitTEXTTOBASE64URL_fun(mathParser.TEXTTOBASE64URL_funContext context);
    Result VisitMD5_fun(mathParser.MD5_funContext context);
    Result VisitREPLACE_fun(mathParser.REPLACE_funContext context);
    Result VisitACOSH_fun(mathParser.ACOSH_funContext context);
    Result VisitISODD_fun(mathParser.ISODD_funContext context);
    Result VisitASC_fun(mathParser.ASC_funContext context);
    Result VisitCOS_fun(mathParser.COS_funContext context);
    Result VisitLN_fun(mathParser.LN_funContext context);
    Result VisitSTRING_fun(mathParser.STRING_funContext context);
    Result VisitHMACMD5_fun(mathParser.HMACMD5_funContext context);
    Result VisitPRODUCT_fun(mathParser.PRODUCT_funContext context);
    Result VisitEXACT_fun(mathParser.EXACT_funContext context);
    Result VisitSUMSQ_fun(mathParser.SUMSQ_funContext context);
    Result VisitSUM_fun(mathParser.SUM_funContext context);
    Result VisitSECOND_fun(mathParser.SECOND_funContext context);
    Result VisitGAMMADIST_fun(mathParser.GAMMADIST_funContext context);
    Result VisitOCT2HEX_fun(mathParser.OCT2HEX_funContext context);
    Result VisitTODAY_fun(mathParser.TODAY_funContext context);
    Result VisitATAN_fun(mathParser.ATAN_funContext context);
    Result VisitE_fun(mathParser.E_funContext context);
    Result VisitTRIM_fun(mathParser.TRIM_funContext context);
    Result VisitRADIANS_fun(mathParser.RADIANS_funContext context);
    Result VisitGAMMALN_fun(mathParser.GAMMALN_funContext context);
    Result VisitTEXT_fun(mathParser.TEXT_funContext context);
    Result VisitFISHER_fun(mathParser.FISHER_funContext context);
    Result VisitAND_fun(mathParser.AND_funContext context);
    Result VisitBIN2HEX_fun(mathParser.BIN2HEX_funContext context);
    Result VisitMULTINOMIAL_fun(mathParser.MULTINOMIAL_funContext context);
    Result VisitMONTH_fun(mathParser.MONTH_funContext context);
    Result VisitURLENCODE_fun(mathParser.URLENCODE_funContext context);
    Result VisitNORMDIST_fun(mathParser.NORMDIST_funContext context);
    Result VisitHMACSHA1_fun(mathParser.HMACSHA1_funContext context);
    Result VisitENDSWITH_fun(mathParser.ENDSWITH_funContext context);
    Result VisitBracket_fun(mathParser.Bracket_funContext context);
    Result VisitBETADIST_fun(mathParser.BETADIST_funContext context);
    Result VisitATANH_fun(mathParser.ATANH_funContext context);
    Result VisitNOW_fun(mathParser.NOW_funContext context);
    Result VisitMEDIAN_fun(mathParser.MEDIAN_funContext context);
    Result VisitPOWER_fun(mathParser.POWER_funContext context);
    Result VisitDEC2OCT_fun(mathParser.DEC2OCT_funContext context);
    Result VisitPROPER_fun(mathParser.PROPER_funContext context);
    Result VisitTRUNC_fun(mathParser.TRUNC_funContext context);
    Result VisitGCD_fun(mathParser.GCD_funContext context);
    Result VisitTANH_fun(mathParser.TANH_funContext context);
    Result VisitHEX2BIN_fun(mathParser.HEX2BIN_funContext context);
    Result VisitSINH_fun(mathParser.SINH_funContext context);
    Result VisitSHA512_fun(mathParser.SHA512_funContext context);
    Result VisitMIN_fun(mathParser.MIN_funContext context);
    Result VisitISNONTEXT_fun(mathParser.ISNONTEXT_funContext context);
    Result VisitABS_fun(mathParser.ABS_funContext context);
    Result VisitROUNDDOWN_fun(mathParser.ROUNDDOWN_funContext context);
    Result VisitIF_fun(mathParser.IF_funContext context);
    Result VisitJOIN_fun(mathParser.JOIN_funContext context);
    Result VisitFIND_fun(mathParser.FIND_funContext context);
    Result VisitSUBSTITUTE_fun(mathParser.SUBSTITUTE_funContext context);
    Result VisitREPT_fun(mathParser.REPT_funContext context);
    Result VisitASIN_fun(mathParser.ASIN_funContext context);
    Result VisitMulDiv_fun(mathParser.MulDiv_funContext context);
    Result VisitREMOVESTART_fun(mathParser.REMOVESTART_funContext context);
    Result VisitT_fun(mathParser.T_funContext context);
    Result VisitWEEKDAY_fun(mathParser.WEEKDAY_funContext context);
    Result VisitBIN2OCT_fun(mathParser.BIN2OCT_funContext context);
    Result VisitBASE64TOTEXT_fun(mathParser.BASE64TOTEXT_funContext context);
    Result VisitTDIST_fun(mathParser.TDIST_funContext context);
    Result VisitDATEVALUE_fun(mathParser.DATEVALUE_funContext context);
    Result VisitSTARTSWITH_fun(mathParser.STARTSWITH_funContext context);
    Result VisitEVEN_fun(mathParser.EVEN_funContext context);
    Result VisitLOGNORMDIST_fun(mathParser.LOGNORMDIST_funContext context);
    Result VisitISNULLOREMPTY_fun(mathParser.ISNULLOREMPTY_funContext context);
    Result VisitTRUE_fun(mathParser.TRUE_funContext context);
    Result VisitFISHERINV_fun(mathParser.FISHERINV_funContext context);
    Result VisitSHA1_fun(mathParser.SHA1_funContext context);
    Result VisitTIME_fun(mathParser.TIME_funContext context);
    Result VisitATAN2_fun(mathParser.ATAN2_funContext context);
    Result VisitRAND_fun(mathParser.RAND_funContext context);
    Result VisitParameter(mathParser.ParameterContext context);
    Result VisitParameter2(mathParser.Parameter2Context context);


    Result VisitExpr2_fun(mathParser.Expr2_funContext context);

    Result VisitVLOOKUP_fun(mathParser.VLOOKUP_funContext context);

    Result VisitLOOKUP_fun(mathParser.LOOKUP_funContext context);

    Result VisitNULL_fun(mathParser.NULL_funContext context);
    Result VisitISNULL_fun(mathParser.ISNULL_funContext context);
    Result VisitISNULLORERROR_fun(mathParser.ISNULLORERROR_funContext context);

    Result VisitDiyFunction_fun(mathParser.DiyFunction_funContext context);
    Result VisitPercentage_fun(mathParser.Percentage_funContext context);
 
}
